
services:
  web:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "8003:8000"  # FastAPI
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/uk_road_risk
      - MAX_MODEL_VERSIONS=5  # Keep only 5 most recent model versions
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - model_data:/app/data/models  # Named volume for models
      - processed_data:/app/data/processed  # Named volume for processed data
    depends_on:
      - db
      - redis
    restart: unless-stopped

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/uk_road_risk
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped

  streamlit:
    build: .
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8502:8501"
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app
    depends_on:
      - api
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=uk_road_risk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

# nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - web
  #     - api
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  model_data:  # Persistent storage for ML models
  processed_data:  # Persistent storage for processed datasets